HW_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    # path('quotes/', include("quotes.urls"))
]

quotes/urls.py
from django.urls import path

from . import views

# app_name = ""

urlpatterns = [
    path('', views.main, name="root"),
    path('<int:page>', views.main, name="root_paginate"),
    path('author/<str:author>/', views.AuthorView.as_view(), name='author'),
    path('tag/<str:tag>/', views.QuotesByTagView.as_view(), name='quotes_by_tag')
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"


urlpatterns = [
    path('login/', views.register, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote_author/', views.add_quote, name='add_quote')
]

quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Tag(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

users/models.py
from django.db import models

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Author, Quote
from django.forms import CharField, TextInput, Textarea, ModelChoiceField, Select


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class AuthorForm(forms.ModelForm):  # new
    fullname = CharField(max_length=50, min_length=2, required=True,
                         widget=TextInput(attrs={"class": "form-control", "id": "exampleInputEmail1"}))
    description = CharField(widget=Textarea)

    class Meta:
        model = Author
        fields = ['fullname', 'description']


class QuoteForm(forms.ModelForm):  # new
    quote = forms.CharField(widget=forms.Textarea)
    author = forms.ModelChoiceField(queryset=Author.objects.all(), widget=forms.Select(attrs={"class": "form-select"}))

    class Meta:
        model = Quote
        fields = ['quote', 'author']

    def __init__(self, *args, **kwargs):
        super(QuoteForm, self).__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.all()

quotes/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from .models import Author, Quote, Tag
from .utils import get_mongodb
from django.core.paginator import Paginator


# Create your views here.

def main(request, page=1):
    db = get_mongodb()
    quotes = db.quotes.find()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={"quotes": quotes_on_page})


class AuthorView(DetailView):
    model = Author
    template_name = 'quotes/about_author.html'
    context_object_name = 'author'
    slug_field = 'fullname'
    slug_url_kwarg = 'author'


class QuotesByTagView(DetailView):
    model = Tag
    template_name = 'quotes/tag_detail.html'
    context_object_name = 'tag'
    slug_field = 'name'
    slug_url_kwarg = 'quote'  # tag

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegistrationForm, AuthorForm, QuoteForm
from django.contrib.auth import logout, authenticate, login
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Author, Quote


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)

            if user is not None:
                login(request, user)
                messages.info(request, 'Registration successful')
                return redirect('/')
    else:
        form = UserRegistrationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.info(request, 'You have logged out of your account')
    return redirect('/')


@login_required
def add_author(request):
    author_instance = Author.objects.first()
    form = AuthorForm(instance=author_instance)
    if request.method == 'POST':
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            author = form.save(commit=False)
            author.save()
            return redirect(to='/')
    return render(request, 'users/add_author.html', context={"form": form})


@login_required
def add_quote(request):
    quote_instance = Quote.objects.first()
    form = QuoteForm(instance=quote_instance)
    if request.method == 'POST':
        form = QuoteForm(request.POST, instance=Quote())
        if form.is_valid():
            quote = form.save(commit=False)
            quote.save()
            return redirect(to='/page/1')
    return render(request, 'users/add_quote_author.html', context={"form": form})

# @login_required  # new
# def add_author(request):
#     if request.method == 'GET':
#         return render(request, 'users/add_author.html')
#     elif request.method == 'POST':
#         return HttpResponse('Author added successfully!')
#     else:
#         return HttpResponse(status=405)
#
#
# @login_required  # new
# def add_author_end_quote(request):
#     if request.method == 'GET':
#         return render(request, 'users/add_quote_author.html')
#     elif request.method == 'POST':
#         return HttpResponse('Author added successfully!')
#     else:
#         return HttpResponse(status=405)

quotes/templates/quotes/about_author.html
{% extends 'quotes/base.html' %}

{% block content %}
    <h1>{{ author.fullname }}</h1>
    {% if author %}
        <h5>Born Date:</h5> <p>{{ author.born_date }}</p>
        <h5>Born Location:</h5> <p>{{ author.born_location }}</p>
        <h5>Description:</h5> <p>{{ author.description }}</p>
    {% else %}
        <p>Author not found </p>
    {% endif %}

{% endblock %}

quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>HomeWork</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4" style="text-align: right;">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}" style="font-size: 20px;">Logout</a>
                <a href="{% url 'users:add_author' %}" style="font-size: 20px; margin-left: 10px;">Add Author</a>
                <a href="{% url 'users:add_quote' %}" style="font-size: 20px; margin-left: 10px;">Add Quote</a>
                {% else %}
                <a href="{% url 'users:login' %}" style="font-size: 20px;">Login</a>
                {% endif %}
            </p>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>

    {% block content %}
    {% endblock %}

</div>
</body>
</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{ quote.author|author }}">(about)</a>

            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>

                {% endfor %}
            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                        <span aria-hidden="true">←</span> Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>
</div>

{% endblock %}

quotes/templates/quotes/tag_detail.html
{% extends 'quotes/base.html' %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
    <title>Tag Details</title>
</head>
<body>

<h1>Details for Tag "{{ tag.name }}"</h1>

<p>Other details about the tag:</p>
<ul>
    <li>Tag name: {{ tag.name }}</li>
    <!-- Додайте інші властивості тегу, які ви хочете відобразити -->
</ul>

<!-- Отримання цитат, пов'язаних з цим тегом -->
<div class="quotes-by-tag">
    <h2>Quotes tagged as "{{ tag.name }}":</h2>
    <ul>
        {% for quote in tag.quote_set.all %}
            <li>{{ quote.quote }}</li>
        {% endfor %}
    </ul>
</div>

</body>
</html>

{% endblock %}

users/templates/users/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center">Create Author</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="author">Author:</label>
            <input type="text" class="form-control" id="author" name="author" style="width: 300px;">
        </div>
        <div class="form-group">
            <label for="text">Post Text:</label>
            <textarea class="form-control" id="text" name="text" rows="8"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}

users/templates/users/add_quote_author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4 text-center">Create Quote</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="author">Author:</label>
            <input type="text" class="form-control" id="author" name="author" style="width: 200px;">
        </div>
        <div class="form-group">
            <label for="text">Post Quote:</label>
            <textarea class="form-control" id="text" name="text" rows="3" style="width: 600px;"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container" style="text-align: right-align;">
    <div class="row header-box">
        <div class="col-md-8">

        </div>

    </div>

    <form action="{% url 'users:login' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="row">
            <form action="{% url 'users:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username:</label>
                    <input type="text" class="form-control" id="username" name="username" required style="width: 200px;">
                </div>
                <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password" required style="width: 200px;">
                </div>

                <div class="form-group" style="margin-top: 20px;">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>

        </div>
    </form>
</div>
{% endblock %}

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
    <h1>Logged out successfully!</h1>
</body>
</html>